### PR TITLE
Sample Project Update

### PR DESCRIPTION
**Pull request by jondong**
Updated SampleApp.xcodeproj, and Updated XWalkView with Swift 1.2 features.

### CODE REVIEW

**Comment by jondong** [comment]
@zliang7 PTAL

**Comment by jondong** [comment]
it seems Travis-CI still uses Xcode 6.2 below. will push the 6.3 modification patch later.

**Comment by zliang7** [comment]
Could you please update the comment, since this change doesn't include updates for swift-1.2?

**Comment by jondong** [comment]
Removed Swift 1.2 modification commit, and updated this Pull Request's title. @zliang7 PTAL

**Pull request merged**
